services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    read_only: true
    tmpfs:
      - /var/run/headscale
    volumes:
      - ./config:/etc/headscale:ro
      - ./lib:/var/lib/headscale
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9090:9090"
      - "3478:3478/udp"
    restart: unless-stopped
    command: serve
    healthcheck:
        test: ["CMD", "headscale", "health"]
    networks:
      - ad-net

networks:
  ad-net:
    external: true