input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # 不再增加 env 字段
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{appName}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug } # 调试用，可去掉
}