services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./logs:/var/log/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - ad-net

networks:
  ad-net:
    external: true