services:
  minio:
    image: cgr.dev/chainguard/minio:latest
    container_name: minio
    user: "0:0"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    networks:
      - ad-net

networks:
  ad-net:
    external: true
